{
  "68f91233d09d156c406bffea778bee14" : {
    "statistic" : {
      "failed" : 1,
      "broken" : 0,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "5e7ccbf1b213cb56",
      "status" : "failed",
      "statusDetails" : "The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Network location provider at 'https://www.googleapis.com/' : No response received.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
      "time" : {
        "start" : 1625760052611,
        "stop" : 1625760059724,
        "duration" : 7113
      }
    } ]
  }
}